use crate::types::{KawaiiLabGroup, KawaiiLabMember};

pub fn get_kawaii_lab_data() -> Vec<KawaiiLabGroup> {
    vec![
        KawaiiLabGroup {
            name: "FRUITS ZIPPER".to_string(),
            name_katakana: "フルーツジッパー".to_string(),
            common_name: "ふるっぱー".to_string(),
            members: vec![
                KawaiiLabMember {
                    name: "月足 天音".to_string(),
                    name_kana: "つきあし あまね".to_string(),
                    nickname: "あまねき".to_string(),
                    color: "赤".to_string(),
                    birthday: "1999-10-26".to_string(),
                    from: "福岡県柳川市".to_string(),
                    height: "153cm".to_string(),
                    blood_type: Some("O".to_string()),
                },
                KawaiiLabMember {
                    name: "鎮西 寿々歌".to_string(),
                    name_kana: "ちんぜい すずか".to_string(),
                    nickname: "おすず".to_string(),
                    color: "オレンジ".to_string(),
                    birthday: "1998-11-24".to_string(),
                    from: "兵庫県西宮市".to_string(),
                    height: "162cm".to_string(),
                    blood_type: Some("AB".to_string()),
                },
                KawaiiLabMember {
                    name: "早瀬 ノエル".to_string(),
                    name_kana: "はやせ のえる".to_string(),
                    nickname: "ノエちゃん".to_string(),
                    color: "黄".to_string(),
                    birthday: "2003-12-29".to_string(),
                    from: "ドイツ・ミュンヘン".to_string(),
                    height: "156cm".to_string(),
                    blood_type: Some("A".to_string()),
                },
                KawaiiLabMember {
                    name: "櫻井 優衣".to_string(),
                    name_kana: "さくらい ゆい".to_string(),
                    nickname: "ゆいちゃん".to_string(),
                    color: "ミントグリーン".to_string(),
                    birthday: "2000-02-21".to_string(),
                    from: "東京都".to_string(),
                    height: "157cm".to_string(),
                    blood_type: Some("B".to_string()),
                },
                KawaiiLabMember {
                    name: "真中 まな".to_string(),
                    name_kana: "まなか まな".to_string(),
                    nickname: "まなふぃ".to_string(),
                    color: "水色（空色）".to_string(),
                    birthday: "1999-04-22".to_string(),
                    from: "神奈川県".to_string(),
                    height: "163cm".to_string(),
                    blood_type: Some("B".to_string()),
                },
                KawaiiLabMember {
                    name: "仲川 瑠夏".to_string(),
                    name_kana: "なかがわ るな".to_string(),
                    nickname: "るなぴ".to_string(),
                    color: "紫".to_string(),
                    birthday: "1997-07-03".to_string(),
                    from: "神奈川県".to_string(),
                    height: "154cm".to_string(),
                    blood_type: Some("O".to_string()),
                },
                KawaiiLabMember {
                    name: "松本 かれん".to_string(),
                    name_kana: "まつもと かれん".to_string(),
                    nickname: "まつかれ、かれんたん".to_string(),
                    color: "ピンク（ベビーピンク）".to_string(),
                    birthday: "2002-03-28".to_string(),
                    from: "千葉県".to_string(),
                    height: "159cm".to_string(),
                    blood_type: Some("O".to_string()),
                },
            ],
        },
        KawaiiLabGroup {
            name: "CANDY TUNE".to_string(),
            name_katakana: "キャンディーチューン".to_string(),
            common_name: "きゃんちゅー".to_string(),
            members: vec![
                KawaiiLabMember {
                    name: "立花 琴未".to_string(),
                    name_kana: "たちばな ことみ".to_string(),
                    nickname: "こっちゃん".to_string(),
                    color: "赤".to_string(),
                    birthday: "2002-05-25".to_string(),
                    from: "福岡県北九州市".to_string(),
                    height: "165cm".to_string(),
                    blood_type: Some("O".to_string()),
                },
                KawaiiLabMember {
                    name: "南 なつ".to_string(),
                    name_kana: "みなみ なつ".to_string(),
                    nickname: "なったん".to_string(),
                    color: "オレンジ".to_string(),
                    birthday: "2001-03-17".to_string(),
                    from: "東京都".to_string(),
                    height: "156cm".to_string(),
                    blood_type: None,
                },
                KawaiiLabMember {
                    name: "小川 奈々子".to_string(),
                    name_kana: "おがわ ななこ".to_string(),
                    nickname: "なちこ、なちさん、なち".to_string(),
                    color: "ミントグリーン".to_string(),
                    birthday: "1999-10-01".to_string(),
                    from: "北海道".to_string(),
                    height: "160cm".to_string(),
                    blood_type: None,
                },
                KawaiiLabMember {
                    name: "福山 梨乃".to_string(),
                    name_kana: "ふくやま りの".to_string(),
                    nickname: "りのまる".to_string(),
                    color: "水色".to_string(),
                    birthday: "1997-12-24".to_string(),
                    from: "東京都".to_string(),
                    height: "155cm".to_string(),
                    blood_type: None,
                },
                KawaiiLabMember {
                    name: "桐原 美月".to_string(),
                    name_kana: "きりはら みづき".to_string(),
                    nickname: "きりちゃん、きりこ、きり".to_string(),
                    color: "青".to_string(),
                    birthday: "2003-02-21".to_string(),
                    from: "茨城県".to_string(),
                    height: "148cm".to_string(),
                    blood_type: None,
                },
                KawaiiLabMember {
                    name: "宮野 静".to_string(),
                    name_kana: "みやの しずか".to_string(),
                    nickname: "しーちゃん".to_string(),
                    color: "紫".to_string(),
                    birthday: "2002-05-30".to_string(),
                    from: "神奈川県".to_string(),
                    height: "157cm".to_string(),
                    blood_type: Some("B".to_string()),
                },
                KawaiiLabMember {
                    name: "村川 緋杏".to_string(),
                    name_kana: "むらかわ びびあん".to_string(),
                    nickname: "びびちゃん、びび".to_string(),
                    color: "ピンク".to_string(),
                    birthday: "1999-12-03".to_string(),
                    from: "福岡県福岡市".to_string(),
                    height: "158cm".to_string(),
                    blood_type: Some("O".to_string()),
                },
            ],
        },
        KawaiiLabGroup {
            name: "SWEET STEADY".to_string(),
            name_katakana: "スウィート・ステディ".to_string(),
            common_name: "すいすて".to_string(),
            members: vec![
                KawaiiLabMember {
                    name: "白石 まゆみ".to_string(),
                    name_kana: "しらいし まゆみ".to_string(),
                    nickname: "まゆみん".to_string(),
                    color: "赤".to_string(),
                    birthday: "2000-12-27".to_string(),
                    from: "東京都".to_string(),
                    height: "166cm".to_string(),
                    blood_type: None,
                },
                KawaiiLabMember {
                    name: "庄司 なぎさ".to_string(),
                    name_kana: "しょうじ なぎさ".to_string(),
                    nickname: "なぎゅ".to_string(),
                    color: "オレンジ".to_string(),
                    birthday: "2000-10-29".to_string(),
                    from: "北海道".to_string(),
                    height: "154cm".to_string(),
                    blood_type: Some("A".to_string()),
                },
                KawaiiLabMember {
                    name: "山内 咲奈".to_string(),
                    name_kana: "やまうち さきな".to_string(),
                    nickname: "さきなてん".to_string(),
                    color: "黄".to_string(),
                    birthday: "2004-02-29".to_string(),
                    from: "大阪府".to_string(),
                    height: "154cm".to_string(),
                    blood_type: None,
                },
                KawaiiLabMember {
                    name: "音井 結衣".to_string(),
                    name_kana: "おとい ゆい".to_string(),
                    nickname: "おゆい".to_string(),
                    color: "水色".to_string(),
                    birthday: "2001-01-09".to_string(),
                    from: "愛知県".to_string(),
                    height: "150cm".to_string(),
                    blood_type: Some("O".to_string()),
                },
                KawaiiLabMember {
                    name: "奥田 彩友".to_string(),
                    name_kana: "おくだ あゆ".to_string(),
                    nickname: "あゆちゃん".to_string(),
                    color: "青".to_string(),
                    birthday: "2001-01-07".to_string(),
                    from: "福井県".to_string(),
                    height: "170cm".to_string(),
                    blood_type: Some("O".to_string()),
                },
                KawaiiLabMember {
                    name: "塩川 莉世".to_string(),
                    name_kana: "しおかわ りせ".to_string(),
                    nickname: "りせちゃん、塩まる、リセ、りせぴ".to_string(),
                    color: "紫".to_string(),
                    birthday: "2000-07-31".to_string(),
                    from: "山梨県".to_string(),
                    height: "161cm".to_string(),
                    blood_type: Some("A".to_string()),
                },
                KawaiiLabMember {
                    name: "栗田 なつか".to_string(),
                    name_kana: "くりた なつか".to_string(),
                    nickname: "なつか".to_string(),
                    color: "ピンク".to_string(),
                    birthday: "2002-07-19".to_string(),
                    from: "京都府".to_string(),
                    height: "153cm".to_string(),
                    blood_type: None,
                },
            ],
        },
        KawaiiLabGroup {
            name: "CUTIE STREET".to_string(),
            name_katakana: "キューティーストリート".to_string(),
            common_name: "きゅーすと".to_string(),
            members: vec![
                KawaiiLabMember {
                    name: "佐野 愛花".to_string(),
                    name_kana: "さの あいか".to_string(),
                    nickname: "あいか".to_string(),
                    color: "赤".to_string(),
                    birthday: "2000-11-26".to_string(),
                    from: "東京都".to_string(),
                    height: "151cm".to_string(),
                    blood_type: None,
                },
                KawaiiLabMember {
                    name: "川本 笑瑠".to_string(),
                    name_kana: "かわもと えみる".to_string(),
                    nickname: "えみる".to_string(),
                    color: "オレンジ".to_string(),
                    birthday: "2002-04-22".to_string(),
                    from: "神奈川県".to_string(),
                    height: "149cm".to_string(),
                    blood_type: Some("A".to_string()),
                },
                KawaiiLabMember {
                    name: "古澤 里紗".to_string(),
                    name_kana: "ふるさわ りさ".to_string(),
                    nickname: "ふーりー、ふりたん".to_string(),
                    color: "黄".to_string(),
                    birthday: "2000-11-08".to_string(),
                    from: "熊本県".to_string(),
                    height: "158cm".to_string(),
                    blood_type: Some("O".to_string()),
                },
                KawaiiLabMember {
                    name: "板倉 可奈".to_string(),
                    name_kana: "いたくら かな".to_string(),
                    nickname: "かな".to_string(),
                    color: "ミントグリーン".to_string(),
                    birthday: "2001-11-11".to_string(),
                    from: "千葉県".to_string(),
                    height: "157cm".to_string(),
                    blood_type: None,
                },
                KawaiiLabMember {
                    name: "梅田 みゆ".to_string(),
                    name_kana: "うめだ みゆ".to_string(),
                    nickname: "みゆ".to_string(),
                    color: "水色".to_string(),
                    birthday: "2004-09-13".to_string(),
                    from: "熊本県".to_string(),
                    height: "150cm".to_string(),
                    blood_type: Some("O".to_string()),
                },
                KawaiiLabMember {
                    name: "増田 彩乃".to_string(),
                    name_kana: "ますだ あやの".to_string(),
                    nickname: "あやの".to_string(),
                    color: "青".to_string(),
                    birthday: "2003-05-26".to_string(),
                    from: "愛知県".to_string(),
                    height: "157cm".to_string(),
                    blood_type: Some("A".to_string()),
                },
                KawaiiLabMember {
                    name: "真鍋 凪咲".to_string(),
                    name_kana: "まなべ なぎさ".to_string(),
                    nickname: "なべちゃん、なぎ".to_string(),
                    color: "紫".to_string(),
                    birthday: "2004-06-28".to_string(),
                    from: "神奈川県".to_string(),
                    height: "161cm".to_string(),
                    blood_type: None,
                },
                KawaiiLabMember {
                    name: "桜庭 遥花".to_string(),
                    name_kana: "さくらば はるか".to_string(),
                    nickname: "ぱるたん".to_string(),
                    color: "ピンク".to_string(),
                    birthday: "2006-01-29".to_string(),
                    from: "北海道岩見沢市".to_string(),
                    height: "154cm".to_string(),
                    blood_type: None,
                },
            ],
        },
    ]
}
